# Copyright 2024 Maner·Fan
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     https://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 应用信息
app:
  title: Cube Chat | Speek FREELY with Me!
  description: Think as you think and Reach as you reach | 想你所想及你所及
  summary:
  version: '0.0.1'
  terms_of_service:
  contact:
    name: Maner·Fan
    url: https://github.com/manerfan
    email: manerfan@163.com
  license_info:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

# 服务配置
server:
  host: ${SERVER_HOST:0.0.0.0}
  port: ${SERVER_PORT:8080}
  cors:
    allowed_origins:
      - "*"
    allowed_methods:
      - "*"
    allowed_headers:
      - "*"

# 数据仓库配置
repository:
  # data
  data:
    type: ${DATA_TYPE:postgres}
    postgres:
      host: ${POSTGRES_HOST:localhost}
      port: ${POSTGRES_PORT:5432}
      database: ${POSTGRES_DATABASE:cube_chat}
      username: ${POSTGRES_USERNAME:cube_chat}
      password: ${POSTGRES_PASSWORD:cube_chat}
  # storage
  storage:
    type: ${STORAGE_TYPE:local}
  # vector
  vector:
    type: ${VECTOR_TYPE:faiss}
  # cache
  cache:
    type: ${CACHE_TYPE:memory}

# 安全设置
security:
  jwt:
    # openssl rand -hex 32
    secret: ${JWT_SK:793539f7301c380d6ebb002ffae34eccdb04faae6716b5f7bd1a56c3e04853a1}
    algorithm: HS256
    expire_minutes: ${JWT_EXPIRE_MINUTES:2880}
