version: 1
formatters:
  default:
    format: '%(asctime)s [%(levelname)s] [%(name)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  app:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    encoding: utf8
    filename: log/cube-chat/app.log
    maxBytes: 104857600
    backupCount: 10
root:
  level: INFO
  handlers:
    - console
    - app
